---
title: "Junk Book"
output: html_notebook
---

```{r Scatterplots, eval=FALSE}
dance <- ggplot(all_songs, aes(x=num, y=danceability, fill=artist_name, col=artist_name)) + 
  #geom_point() +
  geom_violin() +
  labs(fill='Artist', color='Artist', title='Scatterplot of Danceability') +
  xlab('Track Num') +
  ylab('Danceability') +
  theme(legend.position='left')
energy <- ggplot(all_songs, aes(x=num, y=energy, fill=artist_name, col=artist_name)) + 
  #geom_point() + 
  geom_violin() +
  labs(color='Artist', title='Scatterplot of Energy') +
  xlab('Track Num') +
  ylab('Energy') +
  theme(legend.position='none')
key <- ggplot(all_songs, aes(x=key, fill=artist_name)) + geom_histogram(bins=12) + 
  labs(fill='Artist', title='Histograms of Key') +
  xlab('Key') +
  ylab('Count') +
  facet_grid(~ artist_name) + 
  theme(strip.text=element_text()) +
  theme(legend.position='none')
loud <- ggplot(all_songs, aes(x=num, y=loudness, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Loudness') +
  xlab('Track Num') +
  ylab('Loudness') +
  theme(legend.position='none')
mode <- ggplot(all_songs, aes(x=mode, fill=artist_name)) + geom_histogram(bins=2) + 
  labs(fill='Artist', title='Histogram of Mode') +
  xlab('Mode') +
  ylab('Count') +
  facet_grid( ~ artist_name) +
  scale_x_continuous(breaks=c(0,1)) +
  theme(strip.text=element_text()) +
  theme(legend.position='none')
speech <- ggplot(all_songs, aes(x=num, y=speechiness, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Speechiness') +
  xlab('Track Num') +
  ylab('Speechiness') +
  theme(legend.position='none')
acoust <- ggplot(all_songs, aes(x=num, y=acousticness, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Acousticness') +
  xlab('Track Num') +
  ylab('Acousticness') +
  theme(legend.position='none')
inst <- ggplot(all_songs, aes(x=num, y=instrumentalness, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Instrumentalness') +
  xlab('Track Num') +
  ylab('Instrumentalness') +
  theme(legend.position='none')
live <- ggplot(all_songs, aes(x=num, y=liveness, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Liveness') +
  xlab('Track Num') +
  ylab('Liveness') +
  theme(legend.position='none')
valence <- ggplot(all_songs, aes(x=num, y=valence, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Valence') +
  xlab('Track Num') +
  ylab('Valence') +
  theme(legend.position='none')
tempo <- ggplot(all_songs, aes(x=num, y=tempo, col=artist_name)) + geom_point() + 
  labs(color='Artist', title='Scatterplot of Tempo') +
  xlab('Track Num') +
  ylab('Tempo') +
  theme(legend.position='right')

#dance
#energy
#key
#loud
#mode
#speech
#acoust
#inst
#live
#valence
#tempo
```

```{r Chromagrams, eval=FALSE}
#load('data/novel_samples.RData')

lake_of_fire <- 
    get_tidy_audio_analysis('0ri3xd7X6jvJQTz9T6IE7l') %>% 
    select(segments) %>% unnest(segments) %>% 
    select(start, duration, pitches)
fallen_souls <- 
  get_tidy_audio_analysis('7dOk9Bck00Zv0eeq5m6GoN') %>% 
  select(segments) %>% unnest(segments) %>% 
  select(start, duration, pitches)

db_st_plt <- compmus_long_distance(
    lake_of_fire %>% mutate(pitches = map(pitches, compmus_normalise, 'chebyshev')),
    fallen_souls %>% mutate(pitches = map(pitches, compmus_normalise, 'chebyshev')),
    feature = pitches,
    method = 'euclidean') %>% 
    ggplot(
        aes(
            x = xstart + xduration / 2, 
            width = xduration,
            y = ystart + yduration / 2,
            height = yduration,
            fill = d)) + 
    geom_tile() +
    scale_fill_continuous(type = 'viridis', guide = 'none') +
    labs(x = 'Lake Of Fire (D-Block & S-te-Fan)', y = 'Fallen Souls (D-Block & S-te-Fan)') +
    theme_minimal()

knockout <- 
  get_tidy_audio_analysis('5LSCfqeq1u1GxKogSQFEZn') %>% 
  select(segments) %>% unnest(segments) %>% 
  select(start, duration, pitches)

dbst_dt_plt <- compmus_long_distance(
    lake_of_fire %>% mutate(pitches = map(pitches, compmus_normalise, 'chebyshev')),
    knockout %>% mutate(pitches = map(pitches, compmus_normalise, 'chebyshev')),
    feature = pitches,
    method = 'euclidean') %>% 
    ggplot(
        aes(
            x = xstart + xduration / 2, 
            width = xduration,
            y = ystart + yduration / 2,
            height = yduration,
            fill = d)) + 
    geom_tile() +
    scale_fill_continuous(type = 'viridis', guide = 'none') +
    labs(x = 'Lake Of Fire (D-Block & S-te-Fan)', y = 'Knockout (Da Tweekaz)') +
    theme_minimal()

db_st_plt
dbst_dt_plt
save(db_st_plt, file='plots/lf_fs_ld.RData')
save(dbst_dt_plt, file='plots/lf_ko_ld.RData')
#ggplotly(dbst_dt_plt)
```

```{r Align, eval=FALSE}
lake_of_fire_align <- 
    get_tidy_audio_analysis('0ri3xd7X6jvJQTz9T6IE7l') %>%
    compmus_align(bars, segments) %>% 
    select(bars) %>% unnest(bars) %>% 
    mutate(
        pitches = 
            map(segments, 
                compmus_summarise, pitches, 
                method = 'rms', norm = 'euclidean')) %>% 
    mutate(
        timbre = 
            map(segments, 
                compmus_summarise, timbre, 
                method = 'rms', norm = 'euclidean'))
fallen_souls_align <- 
    get_tidy_audio_analysis('7dOk9Bck00Zv0eeq5m6GoN') %>%
    compmus_align(bars, segments) %>% 
    select(bars) %>% unnest(bars) %>% 
    mutate(
        pitches = 
            map(segments, 
                compmus_summarise, pitches, 
                method = 'rms', norm = 'euclidean')) %>% 
    mutate(
        timbre = 
            map(segments, 
                compmus_summarise, timbre, 
                method = 'rms', norm = 'euclidean'))
knockout_align <- 
    get_tidy_audio_analysis('5LSCfqeq1u1GxKogSQFEZn') %>%
    compmus_align(bars, segments) %>% 
    select(bars) %>% unnest(bars) %>% 
    mutate(
        pitches = 
            map(segments, 
                compmus_summarise, pitches, 
                method = 'rms', norm = 'euclidean')) %>% 
    mutate(
        timbre = 
            map(segments, 
                compmus_summarise, timbre, 
                method = 'rms', norm = 'euclidean'))

darkest_hour_align <- 
    get_tidy_audio_analysis('5DWoPJxISs9VMRCJBzujB6') %>%
    compmus_align(bars, segments) %>% 
    select(bars) %>% unnest(bars) %>% 
    mutate(
        pitches = 
            map(segments, 
                compmus_summarise, pitches, 
                method = 'rms', norm = 'euclidean')) %>% 
    mutate(
        timbre = 
            map(segments, 
                compmus_summarise, timbre, 
                method = 'rms', norm = 'euclidean'))
```

```{r Cepstrograms}
# We can use `compmus_gather_timbre` much like `compmus_gather_chroma` last week to yield a cepstrogram. Try different levels of structure -- Spotify's estimates of beats, bars, or sections -- to see which level is the most meaningful.

lf_cept <- lake_of_fire_align %>% 
    compmus_gather_timbre %>% 
    ggplot(
        aes(
            x = start + duration / 2, 
            width = duration, 
            y = basis, 
            fill = value)) + 
    ggtitle('Cepstrogram Lake of Fire') +
    geom_tile() +
    labs(x = 'Time (s)', y = NULL, fill = 'Magnitude') +
    scale_fill_viridis_c(option = 'A', limits=c(0, 0.8)) +
    theme_classic()
fs_cept <- fallen_souls_align %>% 
    compmus_gather_timbre %>% 
    ggplot(
        aes(
            x = start + duration / 2, 
            width = duration, 
            y = basis, 
            fill = value)) + 
    ggtitle('Cepstrogram Fallen Souls') +
    geom_tile() +
    labs(x = 'Time (s)', y = NULL, fill = 'Magnitude') +
    scale_fill_viridis_c(option = 'A', limits=c(0, 0.8)) +
    theme_classic()
ko_cept <- knockout_align %>% 
    compmus_gather_timbre %>% 
    ggplot(
        aes(
            x = start + duration / 2, 
            width = duration, 
            y = basis, 
            fill = value)) + 
    ggtitle('Cepstrogram Knockout') +
    geom_tile() +
    labs(x = 'Time (s)', y = NULL, fill = 'Magnitude') +
    scale_fill_viridis_c(option = 'A', limits=c(0, 0.8)) +
    theme_classic()

save(lf_cept, file='plots/lf_cept.RData')
save(fs_cept, file='plots/fs_cept.RData')
save(ko_cept, file='plots/ko_cept.RData')
```

```{r Self Similarity Matrices}
#- `compmus_long_distance` to compare to series of audio features against each other using common distance metrics, including:
#    - `manhattan`
#    - `aitchison`
#    - `euclidean`
#    - `cosine`
#    - `angular

lf_ss <- lake_of_fire_align %>% 
    compmus_self_similarity(timbre, 'euclidean') %>% 
    ggplot(
        aes(
            x = xstart + xduration / 2, 
            width = xduration,
            y = ystart + yduration / 2,
            height = yduration,
            fill = d)) + 
    ggtitle('Self Similarity Lake of Fire') +
    geom_tile() +
    coord_fixed() +
    scale_fill_viridis_c(option = 'A', guide = 'none') +
    theme_classic() +
    labs(x = '', y = '')
fs_ss <- fallen_souls_align %>% 
    compmus_self_similarity(timbre, 'euclidean') %>% 
    ggplot(
        aes(
            x = xstart + xduration / 2, 
            width = xduration,
            y = ystart + yduration / 2,
            height = yduration,
            fill = d)) + 
    ggtitle('Self Similarity Fallen Souls') +
    geom_tile() +
    coord_fixed() +
    scale_fill_viridis_c(option = 'A', guide = 'none') +
    theme_classic() +
    labs(x = '', y = '')    
ko_ss <- knockout_align %>% 
    compmus_self_similarity(timbre, 'euclidean') %>% 
    ggplot(
        aes(
            x = xstart + xduration / 2, 
            width = xduration,
            y = ystart + yduration / 2,
            height = yduration,
            fill = d)) + 
    ggtitle('Self Similarity Knockout') +
    geom_tile() +
    coord_fixed() +
    scale_fill_viridis_c(option = 'A', guide = 'none') +
    theme_classic() +
    labs(x = '', y = '')

save(lf_ss, file='plots/lf_ss.RData')
save(fs_ss, file='plots/fs_ss.RData')
save(ko_ss, file='plots/ko_ss.RData')
```

```{r Darkest Hour}
dh_cept <- darkest_hour_align %>% 
    compmus_gather_timbre %>% 
    ggplot(
        aes(
            x = start + duration / 2, 
            width = duration, 
            y = basis, 
            fill = value)) + 
    ggtitle('Cepstrogram Darkest Hour') +
    geom_tile() +
    labs(x = 'Time (s)', y = NULL, fill = 'Magnitude') +
    scale_fill_viridis_c(limits=c(0, 0.8) , option = 'A') +
    theme_classic()
    
dh_ss <- darkest_hour_align %>% 
    compmus_self_similarity(timbre, 'euclidean') %>% 
    ggplot(
        aes(
            x = xstart + xduration / 2, 
            width = xduration,
            y = ystart + yduration / 2,
            height = yduration,
            fill = d)) + 
    ggtitle('Self Similarity Darkest Hour') +
    geom_tile() +
    coord_fixed() +
    scale_fill_viridis_c(option = 'A', guide = 'none') +
    theme_classic() +
    labs(x = '', y = '')

save(dh_cept, file='plots/dh_cept.RData')
save(dh_ss, file='plots/dh_ss.RData')
```

